### ISSUE TITLE
beforeAll in skipped describe.onWindows still runs

### ISSUE THREAD

**Issue by schubev** [qmenoret/jest-os-detection#1]
Let’s say I run the following on GNU/Linux.
```js
describe.onWindows('something', () => {
  beforeAll(() => { /* do some Windows specific stuff */ })
  test.each([1, 2, 3])('test %d', () => { /* test stuff */ })
})
```
Then the tests will be marked as skipped but the contents of `beforeAll` will still be run and fail, once for each test.

**Comment by qmenoret** [comment]
This is also the case with regular jest tests:
```

describe.skip('toto', () => {
  beforeAll(() => {
    console.log('beforeAll')
  })
  beforeEach(() => {
    console.log('beforeEach')
  })
  it('test', () => {
    console.log('test')
  })
})
```
The output of this will be:
```
beforeAll
```
Closing the issue as this is not related to this package. It has been reported to jest already. Please see: https://github.com/facebook/jest/issues/8379
